import Foundation

public protocol LLMInterface {
    func askQuestion(_ question: String, context: String) async throws -> String
    func generateSummary(text: String) async throws -> String
    func generateFlashcards(text: String) async throws -> [Flashcard]
    func loadModel() async throws
    func isModelLoaded() -> Bool
}

public class StubLLMInterface: LLMInterface {
    private var modelLoaded = false
    
    public init() {}
    
    public func loadModel() async throws {
        // Simulate model loading
        try await Task.sleep(nanoseconds: 500_000_000) // 0.5 seconds
        modelLoaded = true
        print("✅ Stub LLM model loaded successfully")
    }
    
    public func isModelLoaded() -> Bool {
        return modelLoaded
    }
    
    public func askQuestion(_ question: String, context: String) async throws -> String {
        guard modelLoaded else {
            throw LLMError.modelNotLoaded
        }
        
        // Simulate processing time
        try await Task.sleep(nanoseconds: 1_000_000_000) // 1 second
        
        return """
        Based on the provided context, here's my answer to your question:
        
        **Question:** \(question)
        
        **Answer:** This is a comprehensive stub answer that demonstrates the expected functionality. In a real implementation, this would be generated by analyzing the context: "\(String(context.prefix(100)))..." and providing relevant insights.
        
        The answer would be contextually relevant and helpful for studying purposes.
        """
    }
    
    public func generateSummary(text: String) async throws -> String {
        guard modelLoaded else {
            throw LLMError.modelNotLoaded
        }
        
        // Simulate processing time
        try await Task.sleep(nanoseconds: 1_500_000_000) // 1.5 seconds
        
        let wordCount = text.split(separator: " ").count
        let preview = String(text.prefix(200))
        
        return """
        **Document Summary**
        
        **Length:** \(wordCount) words
        
        **Key Points:**
        • This document contains important information for studying
        • Multiple concepts are covered in detail
        • The content is suitable for flashcard generation
        
        **Preview:** \(preview)...
        
        **Study Recommendation:** This material is well-suited for creating flashcards and would benefit from active recall practice.
        """
    }
    
    public func generateFlashcards(text: String) async throws -> [Flashcard] {
        guard modelLoaded else {
            throw LLMError.modelNotLoaded
        }
        
        // Simulate processing time
        try await Task.sleep(nanoseconds: 2_000_000_000) // 2 seconds
        
        return [
            Flashcard(
                question: "What is the main topic covered in this document?",
                answer: "The document covers key concepts and information relevant to the subject matter being studied.",
                tags: ["main-concept", "overview"]
            ),
            Flashcard(
                question: "What are the important details mentioned?",
                answer: "The document includes specific details, examples, and explanations that support the main concepts.",
                tags: ["details", "examples"]
            ),
            Flashcard(
                question: "How can this information be applied?",
                answer: "This information can be applied through practice, further study, and real-world application of the concepts.",
                tags: ["application", "practice"]
            ),
            Flashcard(
                question: "What should be remembered for the exam?",
                answer: "Key terms, definitions, relationships between concepts, and practical applications should be prioritized for exam preparation.",
                tags: ["exam-prep", "key-terms"]
            )
        ]
    }
}

public enum LLMError: LocalizedError {
    case modelNotLoaded
    case modelLoadFailed(String)
    case processingFailed(String)
    case invalidInput(String)
    
    public var errorDescription: String? {
        switch self {
        case .modelNotLoaded:
            return "LLM model is not loaded. Please load the model first."
        case .modelLoadFailed(let reason):
            return "Failed to load LLM model: \(reason)"
        case .processingFailed(let reason):
            return "LLM processing failed: \(reason)"
        case .invalidInput(let reason):
            return "Invalid input: \(reason)"
        }
    }
} 