name: FocusAI
options:
  bundleIdPrefix: com.charliemking
  deploymentTarget:
    iOS: 15.0

settings:
  base:
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    SWIFT_VERSION: 5.5

targets:
  FocusAI:
    type: application
    platform: iOS
    sources:
      - FocusAI
      - Resources
    settings:
      base:
        INFOPLIST_FILE: FocusAI/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.charliemking.focusai
    dependencies: []

  FocusAITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: FocusAI

  FocusAIUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UITests
    dependencies:
      - target: FocusAI 